# Generated by Django 5.2.8 on 2025-11-27 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product', 'created_at')},
        ),
    ]
